# Numpy Crash Course

In [1]:
import numpy as np

In [3]:
np.__version__

'1.26.4'

In [5]:
import sys
sys.version

'3.12.7 | packaged by Anaconda, Inc. | (main, Oct  4 2024, 13:17:27) [MSC v.1929 64 bit (AMD64)]'

# Creating Arrays

In [7]:
my_list=[0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [9]:
type(my_list)

list

In [11]:
# We are converting list to array

In [15]:
arr=np.array(my_list)

In [17]:
arr

array([0, 1, 2, 3, 4, 5])

In [19]:
type(arr)

numpy.ndarray

In [21]:
type(my_list)

list

# 1.arange() = It gives the values upto the given range.

In [25]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [27]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
np.arange(3.0)

array([0., 1., 2.])

In [31]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [33]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [35]:
np.arange(20,10)

array([], dtype=int32)

In [37]:
np.arange(-20,10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [39]:
np.arange(-16,10)

array([-16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,  -4,
        -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [89]:
np.arange()  # Atleast stop arg should be given.

TypeError: arange() requires stop to be specified.

In [41]:
np.arange(10,30,5)

array([10, 15, 20, 25])

In [43]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [91]:
np.arange(10,30,5,8)    # It wont take 4 args

TypeError: Cannot interpret '8' as a data type

# 2. Zeros() = Always printing zeros according to the attributes given.

In [93]:
np.zeros(3)   # parameter tuning=system by default gives the parameter.dont write 'zero'. By default it gives float
              # 1D array

array([0., 0., 0.])

In [95]:
np.zeros(5,dtype=int)   # Hyperparameter tuning = user wanted to change system parameter. Here I have changed float to int.

array([0, 0, 0, 0, 0])

In [97]:
np.zeros((2,2),dtype=int)    # 2D array

array([[0, 0],
       [0, 0]])

In [99]:
np.zeros(2,10)  # give 2 brackets otherwise it gives you error.

TypeError: Cannot interpret '10' as a data type

In [51]:
np.zeros((2,10))  

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [103]:
np.zeros((5,10))  # float. rows=5, columns=10

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [101]:
np.zeros((5,10),dtype=int)   # int. rows=5, columns=10

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [319]:
n1=(6,8) # we can write like this as well
print(np.zeros(n1)) # Parameter Tuning

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [321]:
n1=(6,8) # Hyperparamter Tuning
print(np.zeros(n1,dtype=int))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


# 3. Ones() = Always printing ones according to the attributes given.

In [324]:
import numpy as np

In [326]:
np.ones(4)

array([1., 1., 1., 1.])

In [59]:
np.ones(5,dtype=int)

array([1, 1, 1, 1, 1])

In [61]:
np.ones((2,2),dtype=int)

array([[1, 1],
       [1, 1]])

In [63]:
np.ones((5,4),dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [105]:
np.twos((2,3)) # twos is not a function. And its not present in in built functions.

AttributeError: module 'numpy' has no attribute 'twos'

In [107]:
np.three((2,3))

AttributeError: module 'numpy' has no attribute 'three'

# 4. rand() = It gives random values. The output changes each time when you run the code.

In [329]:
rand(6)

NameError: name 'rand' is not defined

In [109]:
rand(3,2)

NameError: name 'rand' is not defined

In [335]:
random.rand(3)

array([0.39168813, 0.25118175, 0.08115249])

In [113]:
np.random.rand(5) # np =package, random=module, rand=function

array([0.15328358, 0.08271044, 0.07885927, 0.53835873, 0.2541663 ])

In [67]:
np.random.rand(3,5)   # Bydefault it gives float values. # output will change everytime.

array([[0.9388349 , 0.11294223, 0.55519992, 0.72954773, 0.05372196],
       [0.46727455, 0.58138684, 0.08581477, 0.77099566, 0.58470779],
       [0.33915914, 0.05405676, 0.79265594, 0.53366745, 0.80660715]])

In [341]:
np.random.rand(3,2) # rows=3, columns=2

array([[0.36164304, 0.82107098],
       [0.19016294, 0.73133759],
       [0.303696  , 0.46821197]])

In [343]:
np.random.rand(4,10,2) # arrays=4, rows=10, columns=2

array([[[0.69503996, 0.49140849],
        [0.0636066 , 0.90450058],
        [0.00746652, 0.31738199],
        [0.56767878, 0.86470071],
        [0.42361978, 0.58051721],
        [0.08005577, 0.93428918],
        [0.72055721, 0.09511549],
        [0.55576225, 0.66980059],
        [0.91391999, 0.51518165],
        [0.35307574, 0.25566349]],

       [[0.24109524, 0.4819998 ],
        [0.56799254, 0.02354632],
        [0.91303076, 0.42553106],
        [0.03317022, 0.33197044],
        [0.94586176, 0.17398453],
        [0.39131119, 0.09922385],
        [0.55043035, 0.16251393],
        [0.69593308, 0.93031795],
        [0.32138793, 0.86152906],
        [0.40302811, 0.95026973]],

       [[0.58496565, 0.26783582],
        [0.63922697, 0.63398148],
        [0.31627489, 0.73386384],
        [0.5857367 , 0.8800803 ],
        [0.74695973, 0.96759511],
        [0.15672257, 0.82227711],
        [0.68154754, 0.87957546],
        [0.78798653, 0.33071193],
        [0.36486923, 0.52483712],
        [0

In [347]:
np.random.randint(10,20,2) # randint(low, high, size): This function generates random integers from a half-open interval [low, high). 
                                   # This means that low is inclusive, and high is exclusive.
                           # low: The lowest integer to be generated. In your example, low is 10.
                           # high: The highest integer to be generated (exclusive). In your example, high is 20. 
                                   # This means that the generated numbers will be less than 20.
                           # size: An integer or tuple of integers defining the shape of the output array. In your example, size is 2.
                                  # This means that the function will return an array containing 2 random integers.

array([11, 14])

In [69]:
np.random.randint(2,4)

2

In [339]:
np.random.randint(10,20,5)  # 10=low, 20=high, 5=no.of values as output.
                           # each time it gives 5 random values as output.

array([13, 14, 15, 14, 12])

In [337]:
np.random.randint(2,6,4) # It only gives integer values. its a default function.

array([3, 3, 2, 4])

In [349]:
 np.random.randint(10,20,(10,10)) # [10,10]= its like 2d matrix and its a tuple.
                                 # low=10,high=20
                                 # It generates values in between 10 to 19.

array([[11, 17, 11, 16, 11, 14, 18, 12, 16, 12],
       [16, 19, 13, 11, 15, 12, 16, 17, 19, 18],
       [11, 17, 12, 17, 14, 16, 15, 18, 15, 19],
       [12, 10, 11, 10, 18, 19, 11, 17, 10, 12],
       [15, 14, 18, 16, 16, 14, 15, 16, 17, 15],
       [12, 10, 15, 15, 17, 14, 10, 16, 19, 16],
       [19, 12, 14, 13, 10, 14, 17, 16, 19, 18],
       [13, 19, 14, 16, 12, 11, 18, 15, 12, 19],
       [13, 10, 15, 19, 15, 15, 14, 17, 14, 17],
       [14, 11, 11, 15, 19, 14, 10, 16, 11, 15]])

# 5. reshape() = It does not modify the underlying data of the array; it only changes how the data is organized.

In [75]:
np.arange(1,13)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [115]:
np.arange(1,13).reshape(3,4)    # 3=rows, 4=columns.logic=> 3*4=12 its a match

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [117]:
np.arange(1,13).reshape(5,4) # logic==> 5*4=20. out of range

ValueError: cannot reshape array of size 12 into shape (5,4)

In [79]:
np.arange(1,13).reshape(12,1) 

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [351]:
np.random.randint(10,40,(10,10))  # It gives random values. Everytime it changes.

array([[15, 29, 17, 19, 21, 27, 21, 22, 21, 10],
       [25, 24, 20, 27, 39, 21, 32, 35, 27, 12],
       [27, 13, 33, 32, 16, 36, 10, 19, 14, 24],
       [35, 21, 16, 32, 19, 16, 23, 37, 20, 29],
       [38, 31, 21, 19, 11, 30, 24, 24, 32, 31],
       [37, 35, 33, 25, 31, 39, 10, 34, 35, 26],
       [16, 35, 16, 23, 27, 30, 20, 17, 33, 39],
       [35, 13, 14, 38, 31, 35, 39, 33, 25, 15],
       [13, 39, 28, 26, 33, 22, 35, 32, 29, 15],
       [24, 16, 31, 16, 24, 22, 20, 11, 22, 38]])

In [121]:
np.arange(1,13).reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [ ]:
# Slicing in matrix

In [123]:
b=np.random.randint(10,20,(5,4))
b

array([[14, 15, 10, 10],
       [16, 14, 13, 17],
       [11, 15, 13, 12],
       [16, 18, 18, 12],
       [14, 14, 11, 12]])

In [125]:
type(b)

numpy.ndarray

In [127]:
b[:] # It prints all the elements

array([[14, 15, 10, 10],
       [16, 14, 13, 17],
       [11, 15, 13, 12],
       [16, 18, 18, 12],
       [14, 14, 11, 12]])

In [129]:
b[1:3] # Here each row is one index value. 3=n-1=>2. so 1 and 2 is output.

array([[16, 14, 13, 17],
       [11, 15, 13, 12]])

In [131]:
 b[3:5] # last two rows as output

array([[16, 18, 18, 12],
       [14, 14, 11, 12]])

In [133]:
b

array([[14, 15, 10, 10],
       [16, 14, 13, 17],
       [11, 15, 13, 12],
       [16, 18, 18, 12],
       [14, 14, 11, 12]])

In [146]:
 b[1,3] # Here rows and columns starts with '0'. that is row=0,1,2,3,4 and columns= 0,1,2,3,
       # So row=1 and column(3)=17
       # so output=17

17

In [148]:
b[4,1] # last row second column digit is '14'

14

In [150]:
b[1,-1] # -1= last element of the first row.

17

In [152]:
b[2,-1] # last element of 2nd row.

12

In [154]:
b[2:3] # start=2ndrow and stop=3 = no.of line row
       # start = inclusive and stop = exclusive

array([[11, 15, 13, 12]])

In [156]:
b[4:5] # start= 4th row and stop = 5th row

array([[14, 14, 11, 12]])

In [161]:
 b[:,1] # this is for column output. : = all and 1= 1st column(index value)
       # ',' is very important. otheriwse it will give output for row.

array([15, 14, 15, 18, 14])

In [163]:
 b[:, 2] # column syntax: [:,column number]

array([10, 13, 13, 18, 11])

In [165]:
b

array([[14, 15, 10, 10],
       [16, 14, 13, 17],
       [11, 15, 13, 12],
       [16, 18, 18, 12],
       [14, 14, 11, 12]])

In [167]:
b[-4,-2] # -4 = last to 4th row and -2 = last to second column.

13

In [169]:
import numpy as np

In [171]:
 n=np.arange(1,101) # Like this you can get any set of numbers you want as a matrix.

In [176]:
n.reshape(5,20)

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
         14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30,  31,  32,  33,
         34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,  53,
         54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,
         74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,  92,  93,
         94,  95,  96,  97,  98,  99, 100]])

In [185]:
b=np.random.randint(10,20,(4,4))
b

array([[18, 11, 11, 14],
       [11, 13, 18, 18],
       [15, 13, 16, 18],
       [13, 14, 14, 14]])

In [187]:
 b[-4,-1] # 1st line last element that is -1th element

14

In [189]:
b[-4:2]

array([[18, 11, 11, 14],
       [11, 13, 18, 18]])

# Operations

In [192]:
a=np.random.randint(10,20,5)
a

array([12, 19, 16, 16, 15])

In [194]:
id(a) # Address of the memory location.

2044052114192

In [196]:
my_list=[0,1,2,3,4,5]
arr=np.array(my_list)
arr

array([0, 1, 2, 3, 4, 5])

In [198]:
arr2=np.random.randint(1,100,(10,10))
arr2

array([[51, 55, 48, 84, 26, 18,  5,  4, 38, 68],
       [ 6, 87, 77, 57, 92, 59, 87, 14,  1, 49],
       [94, 33, 15, 18, 53,  8, 60, 59, 93, 88],
       [13, 28, 55, 91,  2,  1, 75, 65,  4, 86],
       [33,  1, 44,  2, 28, 21, 59, 27, 96,  5],
       [77, 75, 34, 87, 80, 57, 86, 33, 81, 66],
       [68, 52, 56, 79, 82, 71, 68, 78, 44,  1],
       [49, 22, 69, 75, 99,  2, 47, 52, 20, 16],
       [12, 43, 26, 86, 58, 41, 97, 92, 77, 54],
       [63, 28, 39, 94, 56, 34, 46, 49, 30, 61]])

In [200]:
arr2[:]

array([[51, 55, 48, 84, 26, 18,  5,  4, 38, 68],
       [ 6, 87, 77, 57, 92, 59, 87, 14,  1, 49],
       [94, 33, 15, 18, 53,  8, 60, 59, 93, 88],
       [13, 28, 55, 91,  2,  1, 75, 65,  4, 86],
       [33,  1, 44,  2, 28, 21, 59, 27, 96,  5],
       [77, 75, 34, 87, 80, 57, 86, 33, 81, 66],
       [68, 52, 56, 79, 82, 71, 68, 78, 44,  1],
       [49, 22, 69, 75, 99,  2, 47, 52, 20, 16],
       [12, 43, 26, 86, 58, 41, 97, 92, 77, 54],
       [63, 28, 39, 94, 56, 34, 46, 49, 30, 61]])

In [202]:
arr2[:4]

array([[51, 55, 48, 84, 26, 18,  5,  4, 38, 68],
       [ 6, 87, 77, 57, 92, 59, 87, 14,  1, 49],
       [94, 33, 15, 18, 53,  8, 60, 59, 93, 88],
       [13, 28, 55, 91,  2,  1, 75, 65,  4, 86]])

In [204]:
arr2[:-4]

array([[51, 55, 48, 84, 26, 18,  5,  4, 38, 68],
       [ 6, 87, 77, 57, 92, 59, 87, 14,  1, 49],
       [94, 33, 15, 18, 53,  8, 60, 59, 93, 88],
       [13, 28, 55, 91,  2,  1, 75, 65,  4, 86],
       [33,  1, 44,  2, 28, 21, 59, 27, 96,  5],
       [77, 75, 34, 87, 80, 57, 86, 33, 81, 66]])

In [206]:
arr2[-4:]

array([[68, 52, 56, 79, 82, 71, 68, 78, 44,  1],
       [49, 22, 69, 75, 99,  2, 47, 52, 20, 16],
       [12, 43, 26, 86, 58, 41, 97, 92, 77, 54],
       [63, 28, 39, 94, 56, 34, 46, 49, 30, 61]])

In [208]:
arr2[0:5] 

array([[51, 55, 48, 84, 26, 18,  5,  4, 38, 68],
       [ 6, 87, 77, 57, 92, 59, 87, 14,  1, 49],
       [94, 33, 15, 18, 53,  8, 60, 59, 93, 88],
       [13, 28, 55, 91,  2,  1, 75, 65,  4, 86],
       [33,  1, 44,  2, 28, 21, 59, 27, 96,  5]])

In [210]:
arr2

array([[51, 55, 48, 84, 26, 18,  5,  4, 38, 68],
       [ 6, 87, 77, 57, 92, 59, 87, 14,  1, 49],
       [94, 33, 15, 18, 53,  8, 60, 59, 93, 88],
       [13, 28, 55, 91,  2,  1, 75, 65,  4, 86],
       [33,  1, 44,  2, 28, 21, 59, 27, 96,  5],
       [77, 75, 34, 87, 80, 57, 86, 33, 81, 66],
       [68, 52, 56, 79, 82, 71, 68, 78, 44,  1],
       [49, 22, 69, 75, 99,  2, 47, 52, 20, 16],
       [12, 43, 26, 86, 58, 41, 97, 92, 77, 54],
       [63, 28, 39, 94, 56, 34, 46, 49, 30, 61]])

In [212]:
arr2[1,4] # ',' this will give you the particular element

92

In [220]:
arr2[-5,5] # left side = top to bottom it starts with '0'
           # right side = bottom to top it starts with '-1'

57

In [216]:
arr2[-5,-6]

80

In [222]:
arr2

array([[51, 55, 48, 84, 26, 18,  5,  4, 38, 68],
       [ 6, 87, 77, 57, 92, 59, 87, 14,  1, 49],
       [94, 33, 15, 18, 53,  8, 60, 59, 93, 88],
       [13, 28, 55, 91,  2,  1, 75, 65,  4, 86],
       [33,  1, 44,  2, 28, 21, 59, 27, 96,  5],
       [77, 75, 34, 87, 80, 57, 86, 33, 81, 66],
       [68, 52, 56, 79, 82, 71, 68, 78, 44,  1],
       [49, 22, 69, 75, 99,  2, 47, 52, 20, 16],
       [12, 43, 26, 86, 58, 41, 97, 92, 77, 54],
       [63, 28, 39, 94, 56, 34, 46, 49, 30, 61]])

In [224]:
arr2[::-1] # reverse of a matrix

array([[63, 28, 39, 94, 56, 34, 46, 49, 30, 61],
       [12, 43, 26, 86, 58, 41, 97, 92, 77, 54],
       [49, 22, 69, 75, 99,  2, 47, 52, 20, 16],
       [68, 52, 56, 79, 82, 71, 68, 78, 44,  1],
       [77, 75, 34, 87, 80, 57, 86, 33, 81, 66],
       [33,  1, 44,  2, 28, 21, 59, 27, 96,  5],
       [13, 28, 55, 91,  2,  1, 75, 65,  4, 86],
       [94, 33, 15, 18, 53,  8, 60, 59, 93, 88],
       [ 6, 87, 77, 57, 92, 59, 87, 14,  1, 49],
       [51, 55, 48, 84, 26, 18,  5,  4, 38, 68]])

In [226]:
arr2[::-2] # It skips 2 rows and gives output in a reverse

array([[63, 28, 39, 94, 56, 34, 46, 49, 30, 61],
       [49, 22, 69, 75, 99,  2, 47, 52, 20, 16],
       [77, 75, 34, 87, 80, 57, 86, 33, 81, 66],
       [13, 28, 55, 91,  2,  1, 75, 65,  4, 86],
       [ 6, 87, 77, 57, 92, 59, 87, 14,  1, 49]])

In [228]:
 arr2[:-3]

array([[51, 55, 48, 84, 26, 18,  5,  4, 38, 68],
       [ 6, 87, 77, 57, 92, 59, 87, 14,  1, 49],
       [94, 33, 15, 18, 53,  8, 60, 59, 93, 88],
       [13, 28, 55, 91,  2,  1, 75, 65,  4, 86],
       [33,  1, 44,  2, 28, 21, 59, 27, 96,  5],
       [77, 75, 34, 87, 80, 57, 86, 33, 81, 66],
       [68, 52, 56, 79, 82, 71, 68, 78, 44,  1]])

In [230]:
arr

array([0, 1, 2, 3, 4, 5])

In [232]:
arr.max() # It gives maximum value

5

In [234]:
arr.min() # It gives maximum value

0

In [236]:
arr. mean() # It gives mean value i.e., 2.5

2.5

In [238]:
arr.median() # It is because median in not in built function. 
             # Use "from numpy import *" where * = import all numpy libraries.

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [240]:
from numpy import *

In [242]:
median(arr)

2.5

In [244]:
arr3=array([10,20,30,40,50,60,70,80,90,100]) # median() works now
median(arr3)

55.0

In [246]:
arr3.reshape(5,2)

array([[ 10,  20],
       [ 30,  40],
       [ 50,  60],
       [ 70,  80],
       [ 90, 100]])

In [248]:
arr

array([0, 1, 2, 3, 4, 5])

In [250]:
arr.reshape(2,3,order='C') # order='C' is used, the elements are taken from the original array in their original order (1, 2, 3, 4, 5, 6)
                           # And placed into the 2x3 array row by row.
                          # In simple words, orderwise output. 

array([[0, 1, 2],
       [3, 4, 5]])

In [252]:
arr.reshape(2,3,order='F') #The original array arr is [0, 1, 2, 3, 4, 5].
                           # With order='F', the reshape() function fills the new 2x3 array column by column:
                            # The first column is filled with the first two elements: 0 and 1.
                            # The second column is filled with the next two elements: 2 and 3.
                            # The third column is filled with the last two elements: 4 and 5.
                            # output=[0,2,4] & [1,3,5]


array([[0, 2, 4],
       [1, 3, 5]])

In [254]:
 arr.reshape(2,3,order='A') # Its almost same as "Order C"

array([[0, 1, 2],
       [3, 4, 5]])

# Indexing

In [260]:
mat=np.arange(0,100).reshape(10,10)
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [262]:
row=4
col=5

In [264]:
row

4

In [266]:
col

5

In [268]:
mat[row,col]

45

In [270]:
 mat[4,5] # 4=row and 5=column. the integer is "45"

45

In [272]:
 mat[6] # row as output

array([60, 61, 62, 63, 64, 65, 66, 67, 68, 69])

In [274]:
mat[:,6] # Column as output

array([ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96])

In [276]:
mat[4,:]

array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [278]:
mat[:,-1]

array([ 9, 19, 29, 39, 49, 59, 69, 79, 89, 99])

In [280]:
mat[:-1] # difference between the "," and ":"

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89]])

In [282]:
mat[1:4]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [284]:
mat[0:10:3]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [286]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [288]:
 mat[2:6,2:4]    # 2:6: This part specifies the rows to select.
                # row:
                # 2 is the starting row index (inclusive).
                # 6 is the ending row index (exclusive).
                # Therefore, this selects rows with indices 2, 3, 4, and 5.
                 # column:
                # 2:4: This part specifies the columns to select.
                # 2 is the starting column index (inclusive).
                # 4 is the ending column index (exclusive).
                # Therefore, this selects columns with indices 2 and 3.


array([[22, 23],
       [32, 33],
       [42, 43],
       [52, 53]])

In [290]:
mat[4:6,4:8]

array([[44, 45, 46, 47],
       [54, 55, 56, 57]])

In [292]:
mat[6:9,5:8] # row=6:9, that is i want the values from 6th to 8th row. 9-1=8
             # column=5:8 that is i want values from 5th to 7th column. 8-1=7

array([[65, 66, 67],
       [75, 76, 77],
       [85, 86, 87]])

# Masking

In [295]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [297]:
id(mat)

2044052123696

In [299]:
 mat<50 # It gives boolean expression as "True" upto 49 numbers.

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [301]:
mat<=50 # Now 50 also included.

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [303]:
mat[mat<50] # To get integer values. we need to use extra "mat"

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [305]:
mat[mat<=50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [307]:
mat[mat==50]

array([50])

In [309]:
mat[mat>50]

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [311]:
mat[mat>=50]

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
       67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83,
       84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [313]:
mat[mat!=50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])